backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: /images

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog-posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Picture", name: "picture", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}